### ISSUE TITLE
semaphores/sem.c needs a block comment to say what it does

### ISSUE THREAD

**Issue by janpgit** [devnull-cz/unix-linux-prog-in-c-src#12]
It's not clear what this example code is supposed to do.

**Comment by vladak** [comment]
BTW when I try to compile `sem.c` on macOS, I get warnings about `sem_init()` and `sem_destroy()` to be deprecated as noted on https://stackoverflow.com/questions/27736618/why-are-sem-init-sem-getvalue-sem-destroy-deprecated-on-mac-os-x-and-w which has interesting remarks about SYS V semaphores to be more portable than POSIX semaphores.
