### ISSUE TITLE
dyn-lib/mylib.c fails to compile on macOS

### ISSUE THREAD

**Issue by janpgit** [devnull-cz/unix-linux-prog-in-c-src#7]
cc -shared -o libmy.so libmy.o
cc -Wall -pedantic -std=c99 -Wshadow -Wpointer-arith -Wcast-qual -Wstrict-prototypes -Werror=implicit-function-declaration -c ld-lazy.c
ld-lazy.c:51:2: error: This code may only run on Solaris and Linux.
#error This code may only run on Solaris and Linux.
 ^
1 error generated.
make[1]: *** [ld-lazy.o] Error 1
make: *** [dyn-lib] Error 2

For macOS, we need something like:

cc -shared -o libmy.o   -Wl,-undefined,dynamic_lookup libmy.c

**Comment by vladak** [comment]
Conditional compilation is needed to achieve this, i.e. GNU make.

**Comment by vladak** [comment]
Also, instead of `-shared`, `dynamiclib` is needed + different library suffix.
